### ISSUE TITLE
Safari failure with Dropbox token API

### ISSUE THREAD

**Issue by elsigh** [adambrgmn/react-oauth-flow#19]
I have this set up with the Dropbox API but when I try with Safari I get some exceptions. I can't really figure out what's up - Chrome sends the User-Agent header too so I don't really get what's happening.

To be fair, I'm using nextjs and it could be related as well.

```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (_error.js.map, line 0)
[Error] Failed to load resource: Request header field User-Agent is not allowed by Access-Control-Allow-Headers. (token, line 0)
[Error] Fetch API cannot load https://api.dropbox.com/oauth2/token?code=[redacted]
Request header field User-Agent is not allowed by Access-Control-Allow-Headers.
[Error] Error in auth
TypeError: err.json is not a function. (In 'err.json()', 'err.json' is undefined)
(anonymous function) — react-oauth-flow.esm.js:637
promiseReactionJob
	handleError (authreceiver.js:6205)
	handleError (authreceiver.js:5298)
	(anonymous function) (authreceiver.js:5277)
	promiseReactionJob
…
```

The JSON part of the error looks like it's coming from:
```
function fetch2(url, opts) {
  var request = fetch(url, opts);
  return request.then(function (response) {
    if (!response.ok) throw response;
    return response.json();
  }).catch(function (err) {
    return err.json().then(function (errJSON) {
      var error = new Error(err.statusText);
      defineStaticProp(error, 'response', err);
      defineStaticProp(error.response, 'data', errJSON);
      defineStaticProp(error, 'request', request);

      throw error;
    });
  });
}
```

**Comment by elsigh** [comment]
fwiw for fetch I'm using `import "whatwg-fetch";`

**Comment by adambrgmn** [comment]
Hi! Thanks for the report!
This is my fault. I added the User-Agent header without properly testing it. But after some research I have found that browsers doesn't accept setting the User-Agent string...

I'm working on a fix and will release a patch within the next hour!

**Comment by elsigh** [comment]
Cool - thanks!!
Ah, now the text of that error makes more sense. I found that commit and tried setting AppName to the empty string to override but wasn't able to.
Will this get pushed up to NPM as well?

**Comment by adambrgmn** [comment]
It should be om NPM already 🙂

--
Allt gott,
Adam Bergman

**Comment by elsigh** [comment]
Doh, I'm a nerd - Since I didn't see a version bump in `package.json` I assumed incorrectly =)
Thanks @adambrgmn !

**Comment by elsigh** [comment]
yup, totally working in Safari now - thank you!
