### ISSUE TITLE
how to add custom flag to header?

### ISSUE THREAD

**Issue by geminiyellow** [adambrgmn/react-oauth-flow#22]
because my auth server need special flag in http request head, but the code in here:

https://github.com/adambrgmn/react-oauth-flow/blob/f7cb4949a106a1f574eb12dc1bdf4f8b7f71ecb2/src/OauthReceiver/index.js#L81

looks like cannot change outside the library,  so , how to change it?

**Comment by adambrgmn** [comment]
Thanks for your issue! During development of this module I've found that it's actually not as general as I had hoped before. And as you have pointed out the headers are not configurable. 

As of right now I'm swamped in work outside open source, so I wont be able to look into this the coming weeks. But I would very much appreciate a PR from your side if you feel like it!
