### ISSUE TITLE
react-native example?

### ISSUE THREAD

**Issue by woodmicha** [adambrgmn/react-oauth-flow#23]
Not a problem but wondering if you have an example of using this in a react native app?  I assume it's possible but when I try the app doesn't like the document object in your index.js example.  I assume this is because in native there isn't one by default...

**Comment by adambrgmn** [comment]
Hi,
Actually I have no experience with RN, even though I'm curious. But if you want to - feel free to see what's wrong and maybe we can work out a PR!
