### ISSUE TITLE
Client secret used in frontend code

### ISSUE THREAD

**Issue by matthewhuang-camelot** [adambrgmn/react-oauth-flow#37]
This isn't secure / the way OAuth is intended to be done -- the code is supposed to be sent to the implementer's secure server, where it does an exchange with the OAuth platform via the client secret. 

However, OauthSender worked well for me + really excited to see if you develop this further!

**Comment by adambrgmn** [comment]
Hi thanks for your comment!
I recently learned this as well and I will probably deprecate parts of this module (OauthReciever). And put out a warning on the README.

But I will probably keep OauthSender because of it's convenience!
Development is under way and changes will come in a few days.
